################################# Default configuration ###################
baseURL = "https://bnbsystems.org"
title = "BnB Systems"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/gh/devicons/devicon@master/devicon.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[[params.plugins.js]]
link = "https://kit.fontawesome.com/samplekit.js"

############################# Navigation ##################################
[[menu.main]]
name = "About Us"
URL = "about"
weight = 1

[[menu.main]]
name = "Service"
URL = "services"
weight = 2



[[menu.main]]
name = "Founders"
URL = "team"
weight = 4


[[menu.main]]
name = "Case studies"
URL = "case-studies"
weight = 5

[[menu.main]]
name = "Careers"
URL = "careers"
weight = 6

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 7




############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "BnB Systems - Scale Up Your Services"
author = "BnB Systems"
# Google Analitycs
google_analitycs_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key="
map_latitude = "53.5045168,"
map_longitude = "10.985072"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-github" 
#link = "https://github.com/bnbsystems"

[[params.social]]
icon = "ti-book" 
#link = "https://bnbsystems.atlassian.net/wiki/spaces/BS/overview"

[[params.social]]
icon = "ti-trello" 
#link = "https://trello.com/bnbsystems/"

[[params.social]]
icon = "ti-view-grid" 
#link = "https://bnbsystemsworkspace.slack.com/"

[[params.social]]
icon = "ti-calendar" 
#link = "https://calendly.com/bnbsystemsltd"



################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "copyright &copy; 2020 all right reserved"

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
copyright = "copyright et copie; 2020 tous droits réservés"